// Class automatically generated by Dev-C++ New Class wizard
#include <iostream>
#include "commercial.h" // class's header file

using namespace std;
// class constructor
Commercial::Commercial(const char* nom, const char* rue, int codePostal, 
const char* ville, float salaireMensuel, int lesVentes, float leTaux)
:Employe(nom,rue,codePostal,ville,salaireMensuel)
{
	setVentesDuMois(lesVentes);
	setTauxComm(leTaux);
}

Commercial::Commercial()
:Employe()
{
	setVentesDuMois(0);
	setTauxComm(0.0);
}

Commercial::Commercial(Commercial& other)
:Employe(other)
{
        setVentesDuMois(other.getVentesDuMois());
        setTauxComm(other.getTauxComm());
}
// class destructor
Commercial::~Commercial()
{
	// insert your code here
}

Commercial& Commercial::operator=(Commercial& other)
{
     if (&other == this) return (*this);
     Employe::operator =(other);
     setVentesDuMois(other.getVentesDuMois());
     setTauxComm(other.getTauxComm());
     return (*this);
}

// returns the value of ventesDuMois
int Commercial::getVentesDuMois()
{
	return ventesDuMois;
}


// sets the value of ventesDuMois
void Commercial::setVentesDuMois(int x)
{
	ventesDuMois = x;
}


// returns the value of tauxComm
float Commercial::getTauxComm()
{
	return tauxComm;
}


// sets the value of tauxComm
void Commercial::setTauxComm(float x)
{
	tauxComm = x;
}


// No description
void Commercial::saisir()
{
	Employe::saisir();
    cout << "Ventes du mois?" << endl;
	cin >> ventesDuMois;
	cin.ignore();
	cout << "Taux comm?" << endl;
	cin >> tauxComm;
	cin.ignore();
}

// No description
void Commercial::afficher()
{
	Employe::afficher();
	cout << "Ventes du mois  = " << getVentesDuMois() << endl;
	cout << "Taux comm  = " << getTauxComm() << endl;
}
