// Class automatically generated by Dev-C++ New Class wizard

#ifndef COMMERCIAL_H
#define COMMERCIAL_H

#include "employe.h" // inheriting class's header file

// No description
class Commercial : public Employe
{
	public:
		// class constructor
		Commercial(char* unNom, char* uneRue, int unCodePostal, char* uneVille, float unSalaireMensuel, int desVentes, float unTaux);
		Commercial();
                Commercial(Commercial& other);
                Commercial& operator=(Commercial& other);
		~Commercial();
		// No description
		void afficher();
		// No description
		void saisir();
		void setTauxComm(float x); // sets the value of tauxComm
		float getTauxComm(); // returns the value of tauxComm
    	void setVentesDuMois(int x); // sets the value of ventesDuMois
		int getVentesDuMois(); // returns the value of ventesDuMois
                virtual Employe* getClone() {return new Commercial(*this);}
        private:
		// No description
		int ventesDuMois;
		float tauxComm;
};

#endif // COMMERCIAL_H
