// Class automatically generated by Dev-C++ New Class wizard

#ifndef EMPLOYE_H
#define EMPLOYE_H

#include "Personne.h" // inheriting class's header file

// No description
class Employe : public Personne
{
    public:
		// class constructor
		Employe(const char* unNom, const char* uneRue, int unCodePostal,
		const char* uneVille, float unSalaireMensuel);
		Employe();
                Employe(Employe& other);
                Employe& operator=(Employe& other);
		// class destructor
		~Employe();
		void SetsalaireMensuel(float x); // sets the value of salaireMensuel
		float GetsalaireMensuel(); // returns the value of salaireMensuel
		// No description
		virtual void saisir();
		// No description
		virtual void afficher();
                //M�thode polymorphe qui renvoie un duplicata de Employe
                virtual Employe* getClone() {return new Employe(*this);}
	private:
		// No description
		float salaireMensuel;
};

#endif // EMPLOYE_H
