// Class automatically generated by Dev-C++ New Class wizard
#include <string.h>
#include "Adresse.h"
#include "Personne.h" // class's header file
#include <iostream>

using namespace std;

int Personne::nbInstance = 0;

// class constructor
Personne::Personne(char* unNom, char* uneRue, int unCodePostal, char* uneVille)
:adresse(uneRue, unCodePostal, uneVille)
{
	setNom(unNom);
	nbInstance++;
}

// class default constructor
Personne::Personne()
{
	setNom("anonyme");
	nbInstance++;
}

Personne::Personne(Personne& other)
:adresse(other.adresse)
{
        setNom(other.getNom());
        nbInstance++;
}
Personne& Personne::operator =(Personne &other)
{
    if (&other == this) return (*this);
    setNom(other.getNom());
    adresse = other.adresse;
//    setAdresse(other.getAdresse());
    return (*this);
}

// class destructor
Personne::~Personne()
{
    nbInstance--;
}

// No description
int Personne::getNbInstance()
{
	return nbInstance;
}

// No description
Adresse Personne::getAdresse()
{
	return adresse;
}
// No description
void Personne::setAdresse(Adresse uneAdresse)
{
	adresse = uneAdresse;
}

// No description
char* Personne::getNom()
{
    return nom;
}

// No description
void Personne::setNom(char* unNom)
{
	strcpy(nom,unNom);
}

void Personne::saisir()
{
    cout << "nom?" << endl;
    cin.getline(nom,50);
    adresse.saisir();
}

void Personne::afficher()
{
    cout << " nom : " << getNom() << endl;
    adresse.afficher();
}
